version: "3.8"

services:
  # Web application service (frontend)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:4000
    depends_on:
      - server
    networks:
      - app-network

  # Server/API service (backend)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-medicare}
      - REDIS_URL=redis://redis:6379
      - PORT=4000
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  # PostgreSQL database
  postgres:
    image: postgres:15
    container_name: medicare-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-medicare}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: medicare-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
