name: Docker Build & Smoke Test

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  docker-build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build & start containers
        run: docker compose -f docker-compose.test.yml up -d --build

      - name: Wait for server healthcheck
        run: |
          echo "Waiting for medicare-server health..."
          for i in {1..10}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' medicare-server || echo "starting")
            echo "Status: $STATUS"
            if [ "$STATUS" = "healthy" ]; then
              echo "✅ Server is healthy"
              exit 0
            fi
            sleep 10
          done
          echo "❌ Server did not get healthy"
          docker compose -f docker-compose.test.yml logs server
          exit 1

      - name: Smoke test API
        run: curl -f http://localhost:4000/health

      - name: Show logs
        if: always()
        run: docker compose -f docker-compose.test.yml logs server

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.test.yml down
